"""Draft a methods-section paragraph from the settings a run actually used."""

from __future__ import annotations

from .expert import ExpertSystem
from .library import SpectralLibrary


def methods_paragraph(meta: dict, expert: ExpertSystem, library: SpectralLibrary) -> str:
    bands = meta["bands_used_nm"]
    sources = sorted({s for s in library.sources if s})
    masks = [f"incidence > {meta['max_incidence_deg']}°" if meta.get("max_incidence_deg") is not None else None,
             f"emission > {meta['max_emission_deg']}°" if meta.get("max_emission_deg") is not None else None,
             f"phase > {meta['max_phase_deg']}°" if meta.get("max_phase_deg") is not None else None]
    masks = [m for m in masks if m]
    mats = [m.name for m in expert.materials if m.name not in meta.get("skipped_materials", {})]

    text = [
        "# Methods (draft generated by lunacorder — edit before use)",
        "",
        f"We analysed Chandrayaan-1 Moon Mineralogy Mapper (M3) Level-2 global-mode reflectance for scene "
        f"{meta['scene']} (rows {meta['rows'][0]}–{meta['rows'][1]}). {len(bands)} bands between "
        f"{bands[0]:.0f} and {bands[-1]:.0f} nm were used; bands flagged in the product's bad-band list and "
        f"bands longward of 2500 nm, which retain residual thermal emission, were excluded."
        + (f" Pixels with {', '.join(masks)} were masked." if masks else ""),
        "",
        f"Reference spectra ({', '.join(sources) or 'laboratory libraries'}) were convolved to each M3 band "
        "using the band's spectral response, reconstructed as the sum of the Gaussian responses of the native "
        "channels binned into it as recorded in the L2 header.",
        "",
        f"Minerals ({', '.join(mats)}) were identified by diagnostic-feature fitting following the Tetracorder "
        "approach (Clark et al., 2003): for each diagnostic absorption a straight-line continuum was removed "
        "from both image and reference spectra, the reference feature was fitted to the image spectrum by "
        "least squares, and the fit (correlation), fitted band depth and its 1σ uncertainty were recorded. "
        "Detections required minimum fit, depth and depth/σ thresholds and the absence of specified "
        f"non-diagnostic bands (expert system '{expert.name}'); the material with the largest fit × depth "
        "was assigned to each pixel.",
    ]
    ens = meta.get("ensemble")
    if ens:
        s = ens["settings"]
        smooth = (f" after Savitzky–Golay smoothing ({s['smooth_window']}-band window)"
                  if s.get("smooth_window") else "")
        text += [
            "",
            "As independent checks, continuum-removed spectra" + smooth + " were compared with every library "
            f"spectrum using the Spectral Angle Mapper (threshold {s['sam_max_rad']} rad; Kruse et al., 1993) "
            f"and Spectral Information Divergence (threshold {s['sid_max']}; Chang, 2000), retaining matches "
            "where both selected the same spectrum. Reflectance spectra were unmixed with fully constrained "
            "linear spectral mixture analysis"
            + (" including a shade endmember" if s.get("lsma_shade") else "")
            + f" (fits with RMSE > {s['lsma_max_rmse']} rejected), using as endmembers the reference spectra "
            "most often selected by feature fitting; because lunar regolith mixes intimately, the fractions "
            "are treated as apparent areal fractions. Constrained Energy Minimisation (Harsanyi, 1993), applied "
            "to continuum-removed band-depth spectra, gave scores that "
            f"were considered detections where ≥ {s['cem_min_score']} and ≥ {s['cem_min_z']} robust standard "
            "deviations above the scene median. For each pixel we report how many of these three methods agree "
            "with the feature-fitting result.",
        ]
    text += ["", "_Check every citation against the publisher's record before submission._", ""]
    return "\n".join(text)
